apiVersion: kueue.x-k8s.io/v1beta1
kind: AdmissionCheck
metadata:
  name: test
spec:
  controllerName: kueue.x-k8s.io/multikueue
  parameters:
    apiGroup: kueue.x-k8s.io
    kind: MultiKueueConfig
    name: test
