apiVersion: batch/v1
kind: Job
metadata:
  generateName: example-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user
    kubernetes-fleet.io/dry-run-crp-ref: work
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      containers:
      - name: sleep
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["30s"]
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Never