apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: work
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: abc.xyz/lmn:latest
        ports:
          - containerPort: 80
