apiVersion: v1
kind: Service
metadata:
  name: fleet-metrics
  namespace: fleet-system
spec:
  selector:
    app.kubernetes.io/name: hub-agent
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080
