apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uber-access
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: uber-access
subjects:
- kind: ServiceAccount
  name: hack
  namespace: default
roleRef:
  kind: ClusterRole
  name: uber-access
  apiGroup: rbac.authorization.k8s.io
